// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @notice The subset of the generated Honk verifier that settlement depends on.
/// @dev Matches the `IVerifier` interface emitted by `bb write_solidity_verifier`.
interface IVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external
        view
        returns (bool);
}

/// @title  DraySettlement
/// @author Joshua Willie
/// @notice On-chain settlement for proofs generated by the Dray proving tier.
///
/// @dev Two things make this contract worth reading.
///
/// **It is circuit-agnostic.** Circuits are registered against a verifier
/// address, and settlement dispatches on a circuit identifier. Adding a circuit
/// is a registration, not a code change. This works because every Dray circuit
/// declares its nullifier as public input 0 (ADR-003), so this contract can
/// find the nullifier without knowing anything else about the circuit's shape.
///
/// **It is the second line of defence against replays, not the first.** The
/// ingest API deduplicates by canonical job hash, but Dray guarantees only
/// at-least-once delivery, so the relayer will eventually submit the same proof
/// twice — after an RPC timeout that actually landed, for instance. The
/// nullifier set makes that harmless: the duplicate reverts, and one submission
/// settles.
contract DraySettlement {
    /// @notice Emitted once per accepted proof.
    /// @param circuitId    Which circuit produced the proof.
    /// @param nullifier    The consumed nullifier, public input 0.
    /// @param relayer      The authorised relayer that submitted it.
    /// @param publicInputs The full public input vector, for off-chain indexing.
    event Settled(
        bytes32 indexed circuitId,
        bytes32 indexed nullifier,
        address indexed relayer,
        bytes32[] publicInputs
    );

    event CircuitRegistered(bytes32 indexed circuitId, address indexed verifier);
    event CircuitDeregistered(bytes32 indexed circuitId);
    event RelayerSet(address indexed relayer, bool authorised);
    event OwnershipTransferred(address indexed from, address indexed to);

    error NotOwner();
    error NotAuthorisedRelayer();
    error UnknownCircuit(bytes32 circuitId);
    error CircuitAlreadyRegistered(bytes32 circuitId);
    error NullifierAlreadyUsed(bytes32 nullifier);
    error InvalidProof();
    error MissingPublicInputs();
    error ZeroAddress();

    /// @notice The trusted operator. Dray is explicitly a trusted-operator
    /// system; this contract does not pretend otherwise.
    address public owner;

    /// @notice circuit identifier => deployed verifier for that circuit.
    mapping(bytes32 => address) public verifierOf;

    /// @notice Addresses permitted to submit settlements.
    mapping(address => bool) public isRelayer;

    /// @notice Nullifiers already consumed. Shared across circuits, which is
    /// safe only because each circuit derives its nullifier under a distinct
    /// domain separator (ADR-003).
    mapping(bytes32 => bool) public nullifierUsed;

    modifier onlyOwner() {
        require(msg.sender == owner, NotOwner());
        _;
    }

    constructor(address initialOwner) {
        require(initialOwner != address(0), ZeroAddress());
        owner = initialOwner;
        emit OwnershipTransferred(address(0), initialOwner);
    }

    // -----------------------------------------------------------------------
    // Settlement
    // -----------------------------------------------------------------------

    /// @notice Verify a proof and consume its nullifier.
    /// @dev Reverts rather than returning false, so that a relayer's transaction
    /// failing is unambiguous in the receipt. The ordering below is deliberate:
    /// the cheap replay check runs before the expensive verification, but the
    /// nullifier is only marked consumed once the proof has actually verified —
    /// an invalid proof must not be able to burn someone else's nullifier.
    /// @param circuitId    The circuit whose verifier should check this proof.
    /// @param proof        The serialised Honk proof.
    /// @param publicInputs Public inputs, with the nullifier at index 0.
    function settle(bytes32 circuitId, bytes calldata proof, bytes32[] calldata publicInputs)
        external
    {
        require(isRelayer[msg.sender], NotAuthorisedRelayer());

        address verifier = verifierOf[circuitId];
        require(verifier != address(0), UnknownCircuit(circuitId));
        require(publicInputs.length != 0, MissingPublicInputs());

        bytes32 nullifier = publicInputs[0];
        require(!nullifierUsed[nullifier], NullifierAlreadyUsed(nullifier));

        // `verify` is a view function reached by staticcall, so it cannot
        // reenter.
        //
        // Note that the generated verifier reverts on an invalid proof rather
        // than returning false, so in practice `settle` usually fails with the
        // verifier's own error — `SumcheckFailed`, `ValueGeFieldOrder` and so
        // on — which is more diagnostic than `InvalidProof` and is deliberately
        // left to propagate. `InvalidProof` covers the contractual case of a
        // verifier that returns false instead.
        require(IVerifier(verifier).verify(proof, publicInputs), InvalidProof());

        nullifierUsed[nullifier] = true;
        emit Settled(circuitId, nullifier, msg.sender, publicInputs);
    }

    /// @notice Whether a proof would settle, without consuming anything.
    ///
    /// @dev For relayer pre-flight: distinguishes a permanently invalid proof
    /// from a transient submission failure, so the relayer can decide whether
    /// retrying is pointless. See the failure taxonomy in Phase 4.
    ///
    /// The `try`/`catch` is load-bearing. The generated Honk verifier does not
    /// return `false` for a bad proof — it reverts, with errors such as
    /// `SumcheckFailed` or `ValueGeFieldOrder`. Calling it directly would make
    /// this function revert too, which would defeat its entire purpose: a
    /// relayer asking "is this proof worth submitting?" must get an answer, not
    /// an exception. Every failure mode is funnelled into `false` here.
    function wouldSettle(bytes32 circuitId, bytes calldata proof, bytes32[] calldata publicInputs)
        external
        view
        returns (bool)
    {
        address verifier = verifierOf[circuitId];
        if (verifier == address(0) || publicInputs.length == 0) return false;
        if (nullifierUsed[publicInputs[0]]) return false;

        try IVerifier(verifier).verify(proof, publicInputs) returns (bool verified) {
            return verified;
        } catch {
            return false;
        }
    }

    // -----------------------------------------------------------------------
    // Administration
    // -----------------------------------------------------------------------

    /// @notice Register a circuit against its verifier.
    /// @dev Deliberately not an upsert. Silently repointing a live circuit at a
    /// different verifier would invalidate every assumption downstream, so
    /// replacing one requires an explicit deregister first.
    function registerCircuit(bytes32 circuitId, address verifier) external onlyOwner {
        require(verifier != address(0), ZeroAddress());
        require(verifierOf[circuitId] == address(0), CircuitAlreadyRegistered(circuitId));
        verifierOf[circuitId] = verifier;
        emit CircuitRegistered(circuitId, verifier);
    }

    function deregisterCircuit(bytes32 circuitId) external onlyOwner {
        require(verifierOf[circuitId] != address(0), UnknownCircuit(circuitId));
        delete verifierOf[circuitId];
        emit CircuitDeregistered(circuitId);
    }

    function setRelayer(address relayer, bool authorised) external onlyOwner {
        require(relayer != address(0), ZeroAddress());
        isRelayer[relayer] = authorised;
        emit RelayerSet(relayer, authorised);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), ZeroAddress());
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }
}
